# Generated by Django 3.1.4 on 2020-12-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskassigned', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='features_web',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
